import streamlit as st
import pandas as pd
import os

# Set page title and icon
st.set_page_config(page_title="Fraud Surveillance", page_icon="🛡️")

st.title("🛡️ Anomaly Surveillance Dashboard")
st.write("Real-time Banking Fraud Detection Interface")

# --- CHECK IF DATA EXISTS ---
DATA_FILE = 'analyzed_data.csv'

if os.path.exists(DATA_FILE):
    # Load the data generated by main.py
    df = pd.read_csv(DATA_FILE)
    
    # --- METRICS BAR ---
    st.divider()
    m1, m2, m3 = st.columns(3)
    m1.metric("Total Records", len(df))
    m2.metric("High Risk Alerts", len(df[df['priority'] == 'High']))
    m3.metric("Avg Risk Score", round(df['risk_score'].mean(), 2))
    
    # --- INVESTIGATION QUEUE ---
    st.subheader("🚩 High-Priority Investigation Queue")
    # Filter for High risk only
    high_priority_df = df[df['priority'] == 'High'].sort_values('risk_score', ascending=False)
    
    if not high_priority_df.empty:
        st.dataframe(high_priority_df[['Transaction ID', 'Amount', 'Merchant Group', 'risk_score']], use_container_width=True)
    else:
        st.success("✅ No High-Risk anomalies detected at this time.")

    # --- VISUAL ANALYSIS ---
    st.subheader("📊 Risk Distribution by Merchant")
    chart_data = df.groupby('Merchant Group')['risk_score'].mean().sort_values(ascending=False)
    st.bar_chart(chart_data)

else:
    # If the file is missing, show this warning instead of a blank screen
    st.error(f"❌ '{DATA_FILE}' not found!")
    st.info("Please run 'python main.py' first to generate the analysis data.")